In [1]:
import torch

In [2]:
a=torch.tensor([10,20,30])
print(a)      

tensor([10, 20, 30])


In [3]:
b=torch.tensor([[1,2],[3,4]])
print(b) 

tensor([[1, 2],
        [3, 4]])


In [ ]:
b=torch.tensor([[1,2,3,4]])
print(b)
b.dim()


tensor([[1, 2, 3, 4]])


2

In [7]:
x=torch.tensor([2,4,5])
y=torch.tensor([1,2,3])
z=x+y
print(z)

tensor([3, 6, 8])


In [8]:
print(x*y)

tensor([ 2,  8, 15])


In [9]:
print(x//y)
print(x%y)
print(x-y)

tensor([2, 2, 1])
tensor([0, 0, 2])
tensor([1, 2, 2])


In [10]:
import torch
t=torch.tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print("Reshaping")
print(t.reshape(6,2))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [11]:
t=torch.tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print("Reshaping")
print(t.reshape(6,3))

Reshaping


RuntimeError: shape '[6, 3]' is invalid for input of size 12

In [12]:
import torch
tensor_1d=torch.tensor([1,2,3,4,5])
print("1D Tensor:",tensor_1d)

1D Tensor: tensor([1, 2, 3, 4, 5])


In [13]:
zero_tensor=torch.zeros(3,4)
print("Zero Tensor:\n",zero_tensor)

Zero Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
one_tensor=torch.ones(2,3)
print("One Tensor:\n",one_tensor)

One Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
